### ISSUE TITLE
i9_v7.2_pinout incorrect label

### ISSUE THREAD

**Issue by CarlFK** [wuxx/Colorlight-FPGA-Projects#10]
https://raw.githubusercontent.com/wuxx/Colorlight-FPGA-Projects/master/doc/i9_v7.2_pinout.png
eth1_4n

If the source was here, I could supply a PR to fix it.

**Comment by wuxx** [comment]
hello, is there any problem with this network

**Comment by CarlFK** [comment]
there are 2 eth1_4n 
p1-6 (I think that is the right name?) should be  eth1_3n

**Comment by wuxx** [comment]
yes, you are right, will update soon, thanks~!
