### ISSUE TITLE
HDMI out of i9+ Ext board not routed to working TDMS balls on xc7a50t

### ISSUE THREAD

**Issue by exitrip** [wuxx/Colorlight-FPGA-Projects#17]
I had to give up on openXC7 toolchain to build larger projects, but Vivado is providing clear errors:

D0+ cannot route to AB6:
![image](https://github.com/wuxx/Colorlight-FPGA-Projects/assets/5750671/3e88b2b7-f45a-4e0b-9b72-191a005f20ce)

D2+ cannot route to W7
![image](https://github.com/wuxx/Colorlight-FPGA-Projects/assets/5750671/0039b06b-3662-49e1-9da6-e0589c530fa1)

Clk/D3+ cannot route to AB7 (which is actually the negative out of AA5):
![image](https://github.com/wuxx/Colorlight-FPGA-Projects/assets/5750671/1d058bea-68f9-404d-bcf6-b14204b5a666)

I'm still looking for an actual datasheet that details the Diff Pair outputs of the xc7a50tfgg484, well enough to work from anything outside of Vivado.

If you want to provide the Design files (either Altium or Kicad) for the Ext board, I'm happy to fix the HDMI pinout myself.
Otherwise this issue is just a note that the HDMI connector does quite work on the Ext board.

**Comment by exitrip** [comment]
This pinout looks like everything is broken out on the DIMM connector close to the current HDMI connector:
![image](https://github.com/wuxx/Colorlight-FPGA-Projects/assets/5750671/7de04689-cc6e-40da-8dac-3e0be0c3fa59)

**Comment by wuxx** [comment]
Hello, in fact HDMI can be implemented by ordinary GPIO, you can refer to here
https://github.com/wuxx/Colorlight-FPGA-Projects/tree/master/src/i5/hdmi_test_pattern

**Comment by exitrip** [comment]
Truly, but using the on-chip hardware will enable higher resolutions and multiple video channels.

**Comment by wuxx** [comment]
understand, the current design is for forward compatibility (colorlight i5 i9)
