### ISSUE TITLE
198MHz on i5 using Vexriscv in Litex, How?

### ISSUE THREAD

**Issue by derekmulcahy** [wuxx/Colorlight-FPGA-Projects#4]
Hi,

Thanks for this repo it is very informative.

I noticed that the litex_with_dram.bit demo file manages to run the Vexriscv processor at 198MHz and achieves high rates of memory access as well. Would it be possible to make the Litex python file available for this demo?

Cheers,
Derek

**Comment by wuxx** [comment]
hello, please check these two examples
litex without dram
https://github.com/wuxx/litexOnColorlightLab004
litex with dram
https://github.com/ghent360/riscvOnColorlight-5A-75B

**Comment by derekmulcahy** [comment]
That info was great. Exactly what I needed.
