### ISSUE TITLE
JTAG STM32F103 firmware

### ISSUE THREAD

**Issue by tuxcnc** [wuxx/Colorlight-FPGA-Projects#5]
Hi.
I'm a little confused with Colorlight-FPGA-Projects/firmware/ folder contens.
I suspect, there are firmware for JTAG, and STM chip can program Lattice FPGA.
But...
One file is 32 kB only and seems it has not all, two other are 128 kB long, but the schematics says there is STM32F103C8T6 with 64 kB flash only...
Can I use the 32 kB file for program Lattice, or must I use CBT6 chip with 128 kB file?
(I need only JTAG made from BluePill, for Colorlight 5A-75B card)
Regards.

**Comment by wuxx** [comment]
hello, the 128KB and 32KB firmware all support JTAG, if you use stm32f103cbt6, can use the 128KB firmware, if c8t6, then need to use the 32KB firmware, these two firmware functions are almost the same.

**Comment by tuxcnc** [comment]
Thanks.
