### ISSUE TITLE
Extra I/O pins for i5 & i9

### ISSUE THREAD

**Issue by chenzhuoyu** [wuxx/Colorlight-FPGA-Projects#8]
Pin-scan shows that there are extra I/O pins on the i5 & i9, as showned below:
![image](https://user-images.githubusercontent.com/8230799/222079186-562055bb-cfb5-49f3-8314-c3e985b6c564.png)

Pin 185 on the DIMM connector is `N.C.` for i5 v7.0, and connected to `U2` for i9 v7.2.

Would you please add these pins to the document, and maybe, if possble, provide a new revision of the break-out board? ;)

**Comment by wuxx** [comment]
Ok, the next version will consider add these IOs
